apiVersion: v1
kind: Service
metadata:
  name: vmi-ubuntu-ssh-svc
  namespace: kubevirt-demo
spec:
  ports:
  - name: ubuntu-ssh-svc
    nodePort: 30001
    port: 27017
    protocol: TCP
    targetPort: 22
  selector:
    special: vmi-ubuntu
  type: NodePort
