apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-ubuntu
  name: vmi-ubuntu
  namespace: kubevirt-demo
spec:
  domain:
    devices:
      disks:
        - disk:
            bus: virtio
          name: containerdisk
        - disk:
            bus: virtio
          name: cloudinitdisk
      interfaces:
        - name: default
          bridge: {}
    resources:
      requests:
        memory: 1024M
  networks:
    - name: default
      pod: {}
  volumes:
    - name: containerdisk
      containerDisk:
        image: atksh/ubuntu-container-disk:latest
    - name: cloudinitdisk
      cloudInitNoCloud:
        userData: |-
          #cloud-config
          ssh_pwauth: True
          chpasswd:
            list: |
              ubuntu:ubuntu
              root:toor
            expire: False
