name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  first-build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: ["python", "python-gpu", "ubuntu-tex", "ubuntu-container-disk"]
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.name }}
          file: ./${{ matrix.name }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.name }}

  second-build-and-push:
    runs-on: ubuntu-latest
    needs: first-build-and-push
    strategy:
      matrix:
        name: ["python-cv", "python-selenium", "python-torch", "python-mkl"]
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.name }}
          file: ./${{ matrix.name }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.name }}
